import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';

export const generateTourPDF = (
    booking: any, 
    agencyName: string = "AXIUS DIGITAL",
    invoiceType: 'UNPAID' | 'PAID' = 'UNPAID',
    isPro: boolean = false // <-- 1. Add the PRO check parameter
) => {
    const doc = new jsPDF();
    const themeColor: [number, number, number] = [13, 165, 255]; // Axius Blue

    // --- 1. HEADER & LOGO ---
    doc.setFillColor(themeColor[0], themeColor[1], themeColor[2]);
    doc.rect(0, 0, 210, 40, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont("helvetica", "bold");
    doc.text(agencyName.toUpperCase(), 20, 25);
    
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.text("PREMIUM TOUR MANAGEMENT", 20, 32);

    // --- MANUAL "PAID" STAMP LOGIC ---
    if (invoiceType === 'PAID') {
        doc.setFillColor(16, 185, 129); // Bright Green
        doc.roundedRect(165, 15, 25, 10, 2, 2, 'F'); 
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.text("PAID", 177.5, 22, { align: 'center' });
    }

    // --- 2. CLIENT & EXPEDITION SUMMARY ---
    doc.setTextColor(40, 40, 40);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text(invoiceType === 'PAID' ? "OFFICIAL RECEIPT" : "BOOKING INVOICE", 20, 55);
    doc.line(20, 57, 190, 57);

    doc.setFontSize(10);
    doc.text("CLIENT DETAILS", 20, 65);
    doc.setFont("helvetica", "normal");
    doc.text(`Name: ${booking.customerName}`, 20, 72);
    doc.text(`Email: ${booking.customerEmail}`, 20, 78);
    doc.text(`Phone: ${booking.customerPhone}`, 20, 84);

    doc.setFont("helvetica", "bold");
    doc.text("TOUR DETAILS", 110, 65);
    doc.setFont("helvetica", "normal");
    doc.text(`Expedition: ${booking.tour?.title || 'Tour Package'}`, 110, 72);
    doc.text(`Date: ${format(new Date(booking.travelDate), 'dd MMM yyyy')}`, 110, 78);
    doc.text(`Travelers: ${booking.numTravelers}`, 110, 84);

    // --- 3. OPTIONAL EXTRAS (ADD-ONS) ---
    let currentY = 95;
    if (booking.selectedAddOns) {
        autoTable(doc, {
            startY: currentY,
            head: [['OPTIONAL UPGRADES', 'STATUS']],
            body: booking.selectedAddOns.split(', ').map((addon: string) => [addon, 'Included']),
            headStyles: { fillColor: [240, 240, 240], textColor: [0, 0, 0], fontStyle: 'bold' },
            margin: { left: 20, right: 20 },
            theme: 'grid'
        });
        currentY = (doc as any).lastAutoTable.finalY + 10;
    }

    // --- 4. FINAL TOTAL ---
    doc.setFillColor(themeColor[0], themeColor[1], themeColor[2]);
    doc.rect(130, currentY, 60, 18, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text(`TOTAL: Rs. ${booking.totalPrice.toLocaleString()}`, 135, currentY + 11);
    
    currentY += 30; 

    // --- 5. THE ITINERARY ---
    const itineraryDays = booking.tour?.itineraryDays || [];
    
    if (itineraryDays.length > 0) {
        if (currentY > 230) {
            doc.addPage();
            currentY = 25;
        }

        doc.setTextColor(themeColor[0], themeColor[1], themeColor[2]);
        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.text("DAY-BY-DAY ITINERARY", 20, currentY);

        const itineraryBody = itineraryDays
            .sort((a: any, b: any) => a.dayNumber - b.dayNumber)
            .map((day: any) => [
                `Day ${day.dayNumber}`,
                day.title,
                day.details.replace(/<[^>]*>/g, '') 
            ]);

        autoTable(doc, {
            startY: currentY + 5,
            head: [['Day', 'Activity', 'Description']],
            body: itineraryBody,
            headStyles: { fillColor: themeColor, textColor: [255, 255, 255] },
            columnStyles: {
                0: { cellWidth: 20, fontStyle: 'bold' },
                1: { cellWidth: 40, fontStyle: 'bold' },
                2: { cellWidth: 'auto' }
            },
            styles: { fontSize: 9, cellPadding: 5 },
            margin: { left: 20, right: 20 },
            pageBreak: 'auto'
        });
    }

    // --- 6. FOOTER & WATERMARK LOGIC ---
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        
        // The standard agency footer (Everyone gets this)
        doc.setTextColor(150, 150, 150);
        doc.setFontSize(8);
        const footerText = invoiceType === 'PAID' 
            ? `This is an official receipt generated by ${agencyName}.`
            : `This is a digital invoice generated by ${agencyName}.`;
        doc.text(footerText, 105, 285, { align: 'center' });

        // THE PRO LOCK: If they are Basic, they get the Travelo stamp
        if (!isPro) {
            doc.setTextColor(200, 200, 200); // Lighter gray so it looks like a real watermark
            doc.setFontSize(7);
            doc.text("Powered by Travelo TMS - Create your own agency portal at travelotms.com", 105, 292, { align: 'center' });
        }
    }

    doc.save(`Invoice_${booking.customerName.replace(/\s+/g, '_')}.pdf`);
};